module Jenkins2
	class CLI
		class CreateSshCredentials < CLI
			def self.description
				'Creates username with ssh private key credentials. Jenkins must have ssh-credentials plugin installed.'
			end

			def add_options
				parser.separator 'Mandatory arguments:'
				parser.on '-u', '--username USER', 'SSH username.' do |u|
					options[:username] = u
				end
				parser.on '-f', '--private-key FILE', 'Path to private key file.' do |f|
					options[:private_key] = f
				end
				parser.on '-s', '--store STORE', 'Path to private key file.' do |f|
					options[:private_key] = f
				end
				parser.on '-d', '--domain DOMAIN', 'Path to private key file.' do |f|
					options[:private_key] = f
				end
				parser.separator ''
				parser.separator "Optional arguments:"
				parser.on '--scope SCOPE', 'Scope of the credentials: global or system. Default - global.' do |d|
					options[:description] = d
				end
				parser.on '--id ID', 'Id of the credential. Will be generated by Jenkins, if ommited.' do |i|
					options[:id] = i
				end
				parser.on '-p', '--passphrase PHRASE', 'Passphrase for the private key. Empty string by default.' do |p|
					options[:passphrase] = p
				end
				parser.on '-d', '--description TEXT', 'Human readable text, what this credentials are used for.' do |d|
					options[:description] = d
				end
			end

			def run
#				jc.credentials.store
			end
		end
	end
end
