image: ruby:2.3

pipelines:
  default:
    - step:
        script:
          - echo "==== Install Jenkins ===="
          - echo "deb http://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
          - apt-get update
          - apt-get install curl jenkins -y --allow-unauthenticated
          - service jenkins start
          - echo "==== Download slave.jar ===="
          - until curl --retry 5 http://localhost:8080/jnlpJars/slave.jar > /tmp/slave.jar; do ; sleep 1; done
          - script/bootstrap
          - export JENKINS2_SERVER='http://localhost:8080/'
          - export JENKINS2_USER='admin'
          - export JENKINS2_KEY=$(cat -- /var/lib/jenkins/secrets/initialAdminPassword)
          - rake ci:all
