# You can use a Docker image from Docker Hub or your own container registry
image: ruby:2.3

pipelines:
  default:
  - step:
      script:
      - export RUBY_ENV='test'
      - script/unit_test
      - rake gem
