# You can use a Docker image from Docker Hub or your own container registry
image: ruby:2.3-slim

pipelines:
  default:
    - step:
        script:
          - script/cibuild
        services:
          - jenkins2
          - docker

definitions:
  services:
    jenkins2:
      image: jenkins/jenkins:lts-alpine

