require_relative 'jenkins2/client'
require_relative 'jenkins2/version'
require_relative 'jenkins2/log'
require_relative 'jenkins2/cli'
require_relative 'jenkins2/connection'
require_relative 'jenkins2/util'
