require_relative 'jenkins2/command_line'
require_relative 'jenkins2/version'
require_relative 'jenkins2/log'
require_relative 'jenkins2/util'
require_relative 'jenkins2/cli'
require_relative 'jenkins2/cli/root'
require_relative 'jenkins2/cli/plugins'
