#!/bin/bash -e

# script/bootstrap: Resolve all dependencies that application requires to run.

sudo=""

if [ "$CI" != 'true' ]; then
	echo "==== Elevating privileges ===="
	sudo="sudo"
fi

echo "==== Install gem dependencies ===="
# On ci server this will be run as normal user, thus installing gem dependencies in user space.
$sudo rake dependencies:install
