#!/bin/sh -e

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

# Set environment to 'test' so other scripts knew, that we are on ci server.
export RUBY_ENV='test'

script/unit_test
script/integration_test

echo "==== Building Gem ===="
rake gem
