#!/bin/sh -e

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

# Set CI to 'true' so other scripts knew, that we are on ci server.
export CI='true'

script/test $@

echo "==== Build gem ===="
rake gem
