#!/usr/bin/env ruby

# script/console: Launch a console for the application. Optionally pass a config file path.

require_relative '../lib/jenkins2'
require 'json'

opts = {}

if ARGV.empty?
	opts[:server] =  'http://' + `kitchen diagnose | grep -oP "(?<=hostname:\\s).*$"`.strip + ':8080'
	opts[:key] = `kitchen exec -c "cat /var/lib/jenkins/secrets/initialAdminPassword"`.split("\n").last.strip
	opts[:user] = 'admin'
else
	opts = JSON.parse( IO.read( ARGV.first ), symbolize_names: true )
end

jc = @jc = Jenkins2::Connection.new( opts[:server] ).basic_auth opts[:user], opts[:key]
puts "Use the '@jc' or 'jc' variable to use the client."

begin
	require 'pry'
	Pry.start
rescue
	IRB.start
end
