#!/bin/sh -x

# script/create_lxd_with_jenkins: Creates an lxd container with Jenkins inside.
# This is used in integtation tests.
echo "==== Create lxd container image with Jenkins from ubuntu/xenial/i386 ===="

codename='xenial'

# download and start container
lxc launch lxd:ubuntu/${codename}/i386 u

# wait for network
sleep 5

# install Jenkins
echo "deb http://pkg.jenkins.io/debian-stable binary/" | lxc file edit u/etc/apt/sources.list.d/jenkins.list
lxc exec u apt-get -- update
lxc exec u apt-get -- install jenkins -y --allow-unauthenticated

# disable setup wizard
lxc exec u sed -- -in '$ a JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"' /etc/default/jenkins

# disable Cross Site Request Forgery protection
lxc exec u sed -- -in '/<crumbIssuer/,/<\/crumbIssuer/d' /var/lib/jenkins/config.xml

# clean future image
lxc exec u apt-get -- clean
lxc exec u apt-get -- autoclean
lxc exec u find -- /var/lib/apt/ -type f -delete
#lxc exec u find -- /var/log/ -type f | while read f; do echo -ne "" > $f; done;
lxc exec u rm -- -f ~/.bash_history

# create image
lxc stop u
lxc publish u --alias=jenkins_test description="$codename with jenkins"
lxc delete u
