#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a TEST or TESTOPTS variable
#              to run a single suite or test.

script/bootstrap
. script/jenkins_start

echo "==== Running tests ===="
rake test:all $@

script/jenkins_kill
