#!/bin/sh -ex

# script/unit_test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

# Bootstrap the application to ensure all gem dependencies are met.
if [ "$RUBY_ENV" = "test" ]; then
	# if executed and the environment is already set to `test`, then we want a
	# clean from scratch application. This almost always means a ci environment,
	# since we set the environment to `test` directly in `script/cibuild`.
	script/bootstrap
	#should be after bootstrap, because otherwise required gem is not installed
	export GENERATE_REPORTS='true'
else
	# if the environment isn't set to `test`, set it to `test` and update the
	# application to ensure all dependencies are met as well as any other things
	# that need to be up to date, like db migrations. The environment not having
	# already been set to `test` almost always means this is being called on it's
	# own from a `development` environment.
	sudo script/bootstrap
	export RUBY_ENV="test"
fi

echo "==== Running unit tests ===="
if [ -f "$1" ]; then
	rake test:unit TEST=$1
else
	rake test:unit
fi
